// Maps the 3-letter ICAO airline codes used in Flighty CSV exports to display names.
// Unrecognized codes are just shown as-is (see csvImport.js) rather than guessed at.
const AIRLINES = {
  UAE: "Emirates",
  MAU: "Air Mauritius",
  IGO: "IndiGo",
  VTI: "Vistara",
  AXM: "AirAsia",
  AIC: "Air India",
  SIA: "Singapore Airlines",
  SWA: "Southwest Airlines",
  NKS: "Spirit Airlines",
  SEJ: "Star Air",
  PHE: "Pawan Hans",
  QTR: "Qatar Airways",
  ETD: "Etihad Airways",
  BAW: "British Airways",
  DAL: "Delta Air Lines",
  UAL: "United Airlines",
  AAL: "American Airlines",
  ACA: "Air Canada",
  KLM: "KLM",
  AFR: "Air France",
  DLH: "Lufthansa",
  THY: "Turkish Airlines",
  CPA: "Cathay Pacific",
  ANA: "All Nippon Airways",
  JAL: "Japan Airlines",
  MAS: "Malaysia Airlines",
  THA: "Thai Airways",
  QFA: "Qantas",
};
